### PR TITLE
Feature/decimal

### PR DESCRIPTION
**Pull request by TKussel**
Decimal Support should be nearly ready to merge. Two todos are still present:

1.  The valid range check only checks the integral part of the value. A check of the integral part is still to be done.
2.  I tried to add support for using a comma as a decimal separator (for input). The validation does not work yet. Any ideas?

Additionally I'm quite unhappy about my changes to ```Perspective1ACreate```: As the ```Study``` object is not yet created, I had to add a private ```fractionalBits``` field for ```shareValues()``` to work.

If we finish the review and are ready for a merge, I will remove the integral ```getAllResults()``` function from Study and rename the decimal version accordingly.

### CODE REVIEW

**Comment by fnwirth** [comment]
>     2\. I tried to add support for using a comma as a decimal separator (for input). The validation does not work yet. Any ideas?

So far I do not understand the problem: When I enter "47.11" or "47,11" in the UI the value is shown as correct and e.g "47;00", "47.000,11", "47,000.11" marks the text box red as an error

**Comment by TKussel** [comment]
Perfect, that id the intended behavior. I seem to have rushed my testing as I  thought that 47,11 resulted in a red text box.

**Comment by prasser** [comment]
@TKussel Would be good if you could check again, just to be sure. This might also have to do with the underlying system's default locale. Whenever textual representations of decimal numbers are handled in software, I would not be surprised by seeing differences across different systems ;)

**Comment by fnwirth** [comment]
>     1. The valid range check only checks the integral part of the value. A check of the integral part is still to be done.

I added seperate checks for integral and fractional parts. Is a check for the entire size of the ring (127^2) actually necessary? If I understood correctly the 32-bit fractional part will be filled with zeros anyways.

**Comment by fnwirth** [comment]
> Additionally I'm quite unhappy about my changes to `Perspective1ACreate`: As the `Study` object is not yet created, I had to add a private `fractionalBits` field for `shareValues()` to work.

Ok. Why is this necessary in the the GUI perspective. Can't his be hidden in  the API (e.g. in Class study?)

**Comment by fnwirth** [comment]
I conducted a GUI test with decimals which worked fine

**Comment by fnwirth** [comment]
> 
> 
> > ```
> > 1. The valid range check only checks the integral part of the value. A check of the integral part is still to be done.
> > ```
> 
> I added a proposal for seperate checks for integral and fractional parts. Is a check for the entire size of the ring (127^2) actually necessary? If I understood correctly the 32-bit fractional part will be filled with zeros anyways.

@TKussel : is my assumption here correct?

**Comment by TKussel** [comment]
There are two cases, where a bounds check may be performed:
 1. The input value is integral. In that case the last 32 bits are zero.
 2. The input value is a double/float. In that case the last 32 bits contain data.

We might perform the check for both cases in the following way:
* We convert the input value to the fixed point representation
* *then* we check, whether ```input < 2^127-1```

ATM the fixed point conversion  is hidden in the ```shareValue()``` API. If you accept the proposed way, I would expose the functionality.

**Comment by fnwirth** [comment]
> 
> 
> There are two cases, where a bounds check may be performed:
> 
>     1. The input value is integral. In that case the last 32 bits are zero.
> 
>     2. The input value is a double/float. In that case the last 32 bits contain data.
> 
> 
> We might perform the check for both cases in the following way:
> 
>     * We convert the input value to the fixed point representation
> 
>     * _then_ we check, whether `input < 2^127-1`
> 
> 
> ATM the fixed point conversion is hidden in the `shareValue()` API. If you accept the proposed way, I would expose the functionality.

Okay I see.
What I committed last week was a check whether the part before the dot is not bigger then 94 bit and a second check for the values behind the dot (if any) is not bigger then 32 bit. 
Wouldnt that already solve the problem?
Or is it better to check the converted (and probably filed with zeros) number for  2^127?

**Comment by TKussel** [comment]
I tested the period/comma decimal separator on multiple systems with German and  US(intl) locale. It works on all tested systems.

> What I committed last week was a check whether the part before the dot is not bigger then 94 bit and a second check for the values behind the dot (if any) is not bigger then 32 bit.
> Wouldnt that already solve the problem?
> Or is it better to check the converted (and probably filed with zeros) number for 2^127?

I'm not certain how BigDecimal stores it's fractional bits. The method you implemented might perform a faulty check because of a possible base 2 / base 10 mismatch. Checking the converted value is safer. Atm the conversion is encapsulated away and I need to expose it.

**Comment by fnwirth** [comment]
Okay, then tell me when its exposed, I can adapt the validation respectivly

**Comment by TKussel** [comment]
> Okay, then tell me when its exposed, I can adapt the validation respectivly

Done in 834eaced6214e945f485dc20d1a000bec5f0df2d

**Comment by fnwirth** [comment]
Added validation in https://github.com/prasser/easy-smpc/pull/85/commits/b6baeb7ba6f4010fbc582eaa39a406d131ba6163

**Comment by TKussel** [comment]
Deprecated functions are removed and the previously necessary awkward naming (```getAllDecResults```, etc.) is cleaned up.

**Comment by fnwirth** [comment]
Merged dirrectly into master, since this PR still realtes to NewFeaturesDuringProjectathon

**Pull request closed without merging**
